// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"mini/database/ent/blog"
	"mini/database/ent/notification"
	"mini/database/ent/schema"
	"mini/database/ent/technician"
	"mini/database/ent/ticket"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogMixin := schema.Blog{}.Mixin()
	blogMixinHooks1 := blogMixin[1].Hooks()
	blog.Hooks[0] = blogMixinHooks1[0]
	blogMixinInters1 := blogMixin[1].Interceptors()
	blog.Interceptors[0] = blogMixinInters1[0]
	blogMixinFields0 := blogMixin[0].Fields()
	_ = blogMixinFields0
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescCreatedAt is the schema descriptor for created_at field.
	blogDescCreatedAt := blogMixinFields0[0].Descriptor()
	// blog.DefaultCreatedAt holds the default value on creation for the created_at field.
	blog.DefaultCreatedAt = blogDescCreatedAt.Default.(func() time.Time)
	// blogDescUpdatedAt is the schema descriptor for updated_at field.
	blogDescUpdatedAt := blogMixinFields0[1].Descriptor()
	// blog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	blog.DefaultUpdatedAt = blogDescUpdatedAt.Default.(func() time.Time)
	// blog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	blog.UpdateDefaultUpdatedAt = blogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// blogDescIsPublished is the schema descriptor for is_published field.
	blogDescIsPublished := blogFields[3].Descriptor()
	// blog.DefaultIsPublished holds the default value on creation for the is_published field.
	blog.DefaultIsPublished = blogDescIsPublished.Default.(bool)
	// blogDescID is the schema descriptor for id field.
	blogDescID := blogFields[0].Descriptor()
	// blog.DefaultID holds the default value on creation for the id field.
	blog.DefaultID = blogDescID.Default.(func() uuid.UUID)
	notificationMixin := schema.Notification{}.Mixin()
	notificationMixinHooks1 := notificationMixin[1].Hooks()
	notification.Hooks[0] = notificationMixinHooks1[0]
	notificationMixinInters1 := notificationMixin[1].Interceptors()
	notification.Interceptors[0] = notificationMixinInters1[0]
	notificationMixinFields0 := notificationMixin[0].Fields()
	_ = notificationMixinFields0
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationMixinFields0[0].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescUpdatedAt is the schema descriptor for updated_at field.
	notificationDescUpdatedAt := notificationMixinFields0[1].Descriptor()
	// notification.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	notification.DefaultUpdatedAt = notificationDescUpdatedAt.Default.(func() time.Time)
	// notification.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	notification.UpdateDefaultUpdatedAt = notificationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// notificationDescIsPublished is the schema descriptor for is_published field.
	notificationDescIsPublished := notificationFields[4].Descriptor()
	// notification.DefaultIsPublished holds the default value on creation for the is_published field.
	notification.DefaultIsPublished = notificationDescIsPublished.Default.(bool)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	technicianMixin := schema.Technician{}.Mixin()
	technicianMixinHooks1 := technicianMixin[1].Hooks()
	technician.Hooks[0] = technicianMixinHooks1[0]
	technicianMixinInters1 := technicianMixin[1].Interceptors()
	technician.Interceptors[0] = technicianMixinInters1[0]
	technicianMixinFields0 := technicianMixin[0].Fields()
	_ = technicianMixinFields0
	technicianFields := schema.Technician{}.Fields()
	_ = technicianFields
	// technicianDescCreatedAt is the schema descriptor for created_at field.
	technicianDescCreatedAt := technicianMixinFields0[0].Descriptor()
	// technician.DefaultCreatedAt holds the default value on creation for the created_at field.
	technician.DefaultCreatedAt = technicianDescCreatedAt.Default.(func() time.Time)
	// technicianDescUpdatedAt is the schema descriptor for updated_at field.
	technicianDescUpdatedAt := technicianMixinFields0[1].Descriptor()
	// technician.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	technician.DefaultUpdatedAt = technicianDescUpdatedAt.Default.(func() time.Time)
	// technician.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	technician.UpdateDefaultUpdatedAt = technicianDescUpdatedAt.UpdateDefault.(func() time.Time)
	// technicianDescID is the schema descriptor for id field.
	technicianDescID := technicianFields[0].Descriptor()
	// technician.DefaultID holds the default value on creation for the id field.
	technician.DefaultID = technicianDescID.Default.(func() uuid.UUID)
	ticketMixin := schema.Ticket{}.Mixin()
	ticketMixinHooks1 := ticketMixin[1].Hooks()
	ticket.Hooks[0] = ticketMixinHooks1[0]
	ticketMixinInters1 := ticketMixin[1].Interceptors()
	ticket.Interceptors[0] = ticketMixinInters1[0]
	ticketMixinFields0 := ticketMixin[0].Fields()
	_ = ticketMixinFields0
	ticketFields := schema.Ticket{}.Fields()
	_ = ticketFields
	// ticketDescCreatedAt is the schema descriptor for created_at field.
	ticketDescCreatedAt := ticketMixinFields0[0].Descriptor()
	// ticket.DefaultCreatedAt holds the default value on creation for the created_at field.
	ticket.DefaultCreatedAt = ticketDescCreatedAt.Default.(func() time.Time)
	// ticketDescUpdatedAt is the schema descriptor for updated_at field.
	ticketDescUpdatedAt := ticketMixinFields0[1].Descriptor()
	// ticket.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ticket.DefaultUpdatedAt = ticketDescUpdatedAt.Default.(func() time.Time)
	// ticket.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ticket.UpdateDefaultUpdatedAt = ticketDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ticketDescTechnicianResponse is the schema descriptor for technician_response field.
	ticketDescTechnicianResponse := ticketFields[6].Descriptor()
	// ticket.DefaultTechnicianResponse holds the default value on creation for the technician_response field.
	ticket.DefaultTechnicianResponse = ticketDescTechnicianResponse.Default.(string)
	// ticketDescCancelReason is the schema descriptor for cancel_reason field.
	ticketDescCancelReason := ticketFields[7].Descriptor()
	// ticket.DefaultCancelReason holds the default value on creation for the cancel_reason field.
	ticket.DefaultCancelReason = ticketDescCancelReason.Default.(string)
	// ticketDescID is the schema descriptor for id field.
	ticketDescID := ticketFields[0].Descriptor()
	// ticket.DefaultID holds the default value on creation for the id field.
	ticket.DefaultID = ticketDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
