// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the ticket type in the database.
	Label = "ticket"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldTicketType holds the string denoting the ticket_type field in the database.
	FieldTicketType = "ticket_type"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIssue holds the string denoting the issue field in the database.
	FieldIssue = "issue"
	// FieldTechnicianResponse holds the string denoting the technician_response field in the database.
	FieldTechnicianResponse = "technician_response"
	// FieldCancelReason holds the string denoting the cancel_reason field in the database.
	FieldCancelReason = "cancel_reason"
	// FieldCustomerName holds the string denoting the customer_name field in the database.
	FieldCustomerName = "customer_name"
	// FieldCustomerPhone holds the string denoting the customer_phone field in the database.
	FieldCustomerPhone = "customer_phone"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// EdgeTechnicians holds the string denoting the technicians edge name in mutations.
	EdgeTechnicians = "technicians"
	// Table holds the table name of the ticket in the database.
	Table = "tickets"
	// TechniciansTable is the table that holds the technicians relation/edge. The primary key declared below.
	TechniciansTable = "ticket_technicians"
	// TechniciansInverseTable is the table name for the Technician entity.
	// It exists in this package in order to avoid circular dependency with the "technician" package.
	TechniciansInverseTable = "technicians"
)

// Columns holds all SQL columns for ticket fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCode,
	FieldTicketType,
	FieldPriority,
	FieldStatus,
	FieldIssue,
	FieldTechnicianResponse,
	FieldCancelReason,
	FieldCustomerName,
	FieldCustomerPhone,
	FieldAddress,
}

var (
	// TechniciansPrimaryKey and TechniciansColumn2 are the table columns denoting the
	// primary key for the technicians relation (M2M).
	TechniciansPrimaryKey = []string{"ticket_id", "technician_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "mini/database/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTechnicianResponse holds the default value on creation for the "technician_response" field.
	DefaultTechnicianResponse string
	// DefaultCancelReason holds the default value on creation for the "cancel_reason" field.
	DefaultCancelReason string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// TicketType defines the type for the "ticket_type" enum field.
type TicketType string

// TicketType values.
const (
	TicketTypeInstallation TicketType = "installation"
	TicketTypeTroubleshoot TicketType = "troubleshoot"
)

func (tt TicketType) String() string {
	return string(tt)
}

// TicketTypeValidator is a validator for the "ticket_type" field enum values. It is called by the builders before save.
func TicketTypeValidator(tt TicketType) error {
	switch tt {
	case TicketTypeInstallation, TicketTypeTroubleshoot:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for ticket_type field: %q", tt)
	}
}

// Priority defines the type for the "priority" enum field.
type Priority string

// PriorityLow is the default value of the Priority enum.
const DefaultPriority = PriorityLow

// Priority values.
const (
	PriorityUrgent Priority = "urgent"
	PriorityHigh   Priority = "high"
	PriorityMedium Priority = "medium"
	PriorityLow    Priority = "low"
)

func (pr Priority) String() string {
	return string(pr)
}

// PriorityValidator is a validator for the "priority" field enum values. It is called by the builders before save.
func PriorityValidator(pr Priority) error {
	switch pr {
	case PriorityUrgent, PriorityHigh, PriorityMedium, PriorityLow:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for priority field: %q", pr)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusNew is the default value of the Status enum.
const DefaultStatus = StatusNew

// Status values.
const (
	StatusNew      Status = "new"
	StatusProgress Status = "progress"
	StatusHold     Status = "hold"
	StatusDone     Status = "done"
	StatusProblem  Status = "problem"
	StatusCancel   Status = "cancel"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusNew, StatusProgress, StatusHold, StatusDone, StatusProblem, StatusCancel:
		return nil
	default:
		return fmt.Errorf("ticket: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Ticket queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByTicketType orders the results by the ticket_type field.
func ByTicketType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTicketType, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIssue orders the results by the issue field.
func ByIssue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssue, opts...).ToFunc()
}

// ByTechnicianResponse orders the results by the technician_response field.
func ByTechnicianResponse(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechnicianResponse, opts...).ToFunc()
}

// ByCancelReason orders the results by the cancel_reason field.
func ByCancelReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancelReason, opts...).ToFunc()
}

// ByCustomerName orders the results by the customer_name field.
func ByCustomerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerName, opts...).ToFunc()
}

// ByCustomerPhone orders the results by the customer_phone field.
func ByCustomerPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomerPhone, opts...).ToFunc()
}

// ByAddress orders the results by the address field.
func ByAddress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddress, opts...).ToFunc()
}

// ByTechniciansCount orders the results by technicians count.
func ByTechniciansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTechniciansStep(), opts...)
	}
}

// ByTechnicians orders the results by technicians terms.
func ByTechnicians(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTechniciansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTechniciansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TechniciansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TechniciansTable, TechniciansPrimaryKey...),
	)
}
