// Code generated by ent, DO NOT EDIT.

package ticket

import (
	"mini/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDeletedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCode, v))
}

// Issue applies equality check predicate on the "issue" field. It's identical to IssueEQ.
func Issue(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldIssue, v))
}

// TechnicianResponse applies equality check predicate on the "technician_response" field. It's identical to TechnicianResponseEQ.
func TechnicianResponse(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTechnicianResponse, v))
}

// CancelReason applies equality check predicate on the "cancel_reason" field. It's identical to CancelReasonEQ.
func CancelReason(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCancelReason, v))
}

// CustomerName applies equality check predicate on the "customer_name" field. It's identical to CustomerNameEQ.
func CustomerName(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCustomerName, v))
}

// CustomerPhone applies equality check predicate on the "customer_phone" field. It's identical to CustomerPhoneEQ.
func CustomerPhone(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCustomerPhone, v))
}

// Address applies equality check predicate on the "address" field. It's identical to AddressEQ.
func Address(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldAddress, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldDeletedAt))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldCode, v))
}

// TicketTypeEQ applies the EQ predicate on the "ticket_type" field.
func TicketTypeEQ(v TicketType) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTicketType, v))
}

// TicketTypeNEQ applies the NEQ predicate on the "ticket_type" field.
func TicketTypeNEQ(v TicketType) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldTicketType, v))
}

// TicketTypeIn applies the In predicate on the "ticket_type" field.
func TicketTypeIn(vs ...TicketType) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldTicketType, vs...))
}

// TicketTypeNotIn applies the NotIn predicate on the "ticket_type" field.
func TicketTypeNotIn(vs ...TicketType) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldTicketType, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...Priority) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldPriority, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldStatus, vs...))
}

// IssueEQ applies the EQ predicate on the "issue" field.
func IssueEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldIssue, v))
}

// IssueNEQ applies the NEQ predicate on the "issue" field.
func IssueNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldIssue, v))
}

// IssueIn applies the In predicate on the "issue" field.
func IssueIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldIssue, vs...))
}

// IssueNotIn applies the NotIn predicate on the "issue" field.
func IssueNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldIssue, vs...))
}

// IssueGT applies the GT predicate on the "issue" field.
func IssueGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldIssue, v))
}

// IssueGTE applies the GTE predicate on the "issue" field.
func IssueGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldIssue, v))
}

// IssueLT applies the LT predicate on the "issue" field.
func IssueLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldIssue, v))
}

// IssueLTE applies the LTE predicate on the "issue" field.
func IssueLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldIssue, v))
}

// IssueContains applies the Contains predicate on the "issue" field.
func IssueContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldIssue, v))
}

// IssueHasPrefix applies the HasPrefix predicate on the "issue" field.
func IssueHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldIssue, v))
}

// IssueHasSuffix applies the HasSuffix predicate on the "issue" field.
func IssueHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldIssue, v))
}

// IssueEqualFold applies the EqualFold predicate on the "issue" field.
func IssueEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldIssue, v))
}

// IssueContainsFold applies the ContainsFold predicate on the "issue" field.
func IssueContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldIssue, v))
}

// TechnicianResponseEQ applies the EQ predicate on the "technician_response" field.
func TechnicianResponseEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldTechnicianResponse, v))
}

// TechnicianResponseNEQ applies the NEQ predicate on the "technician_response" field.
func TechnicianResponseNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldTechnicianResponse, v))
}

// TechnicianResponseIn applies the In predicate on the "technician_response" field.
func TechnicianResponseIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldTechnicianResponse, vs...))
}

// TechnicianResponseNotIn applies the NotIn predicate on the "technician_response" field.
func TechnicianResponseNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldTechnicianResponse, vs...))
}

// TechnicianResponseGT applies the GT predicate on the "technician_response" field.
func TechnicianResponseGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldTechnicianResponse, v))
}

// TechnicianResponseGTE applies the GTE predicate on the "technician_response" field.
func TechnicianResponseGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldTechnicianResponse, v))
}

// TechnicianResponseLT applies the LT predicate on the "technician_response" field.
func TechnicianResponseLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldTechnicianResponse, v))
}

// TechnicianResponseLTE applies the LTE predicate on the "technician_response" field.
func TechnicianResponseLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldTechnicianResponse, v))
}

// TechnicianResponseContains applies the Contains predicate on the "technician_response" field.
func TechnicianResponseContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldTechnicianResponse, v))
}

// TechnicianResponseHasPrefix applies the HasPrefix predicate on the "technician_response" field.
func TechnicianResponseHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldTechnicianResponse, v))
}

// TechnicianResponseHasSuffix applies the HasSuffix predicate on the "technician_response" field.
func TechnicianResponseHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldTechnicianResponse, v))
}

// TechnicianResponseEqualFold applies the EqualFold predicate on the "technician_response" field.
func TechnicianResponseEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldTechnicianResponse, v))
}

// TechnicianResponseContainsFold applies the ContainsFold predicate on the "technician_response" field.
func TechnicianResponseContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldTechnicianResponse, v))
}

// CancelReasonEQ applies the EQ predicate on the "cancel_reason" field.
func CancelReasonEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCancelReason, v))
}

// CancelReasonNEQ applies the NEQ predicate on the "cancel_reason" field.
func CancelReasonNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCancelReason, v))
}

// CancelReasonIn applies the In predicate on the "cancel_reason" field.
func CancelReasonIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCancelReason, vs...))
}

// CancelReasonNotIn applies the NotIn predicate on the "cancel_reason" field.
func CancelReasonNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCancelReason, vs...))
}

// CancelReasonGT applies the GT predicate on the "cancel_reason" field.
func CancelReasonGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCancelReason, v))
}

// CancelReasonGTE applies the GTE predicate on the "cancel_reason" field.
func CancelReasonGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCancelReason, v))
}

// CancelReasonLT applies the LT predicate on the "cancel_reason" field.
func CancelReasonLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCancelReason, v))
}

// CancelReasonLTE applies the LTE predicate on the "cancel_reason" field.
func CancelReasonLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCancelReason, v))
}

// CancelReasonContains applies the Contains predicate on the "cancel_reason" field.
func CancelReasonContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldCancelReason, v))
}

// CancelReasonHasPrefix applies the HasPrefix predicate on the "cancel_reason" field.
func CancelReasonHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldCancelReason, v))
}

// CancelReasonHasSuffix applies the HasSuffix predicate on the "cancel_reason" field.
func CancelReasonHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldCancelReason, v))
}

// CancelReasonEqualFold applies the EqualFold predicate on the "cancel_reason" field.
func CancelReasonEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldCancelReason, v))
}

// CancelReasonContainsFold applies the ContainsFold predicate on the "cancel_reason" field.
func CancelReasonContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldCancelReason, v))
}

// CustomerNameEQ applies the EQ predicate on the "customer_name" field.
func CustomerNameEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCustomerName, v))
}

// CustomerNameNEQ applies the NEQ predicate on the "customer_name" field.
func CustomerNameNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCustomerName, v))
}

// CustomerNameIn applies the In predicate on the "customer_name" field.
func CustomerNameIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCustomerName, vs...))
}

// CustomerNameNotIn applies the NotIn predicate on the "customer_name" field.
func CustomerNameNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCustomerName, vs...))
}

// CustomerNameGT applies the GT predicate on the "customer_name" field.
func CustomerNameGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCustomerName, v))
}

// CustomerNameGTE applies the GTE predicate on the "customer_name" field.
func CustomerNameGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCustomerName, v))
}

// CustomerNameLT applies the LT predicate on the "customer_name" field.
func CustomerNameLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCustomerName, v))
}

// CustomerNameLTE applies the LTE predicate on the "customer_name" field.
func CustomerNameLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCustomerName, v))
}

// CustomerNameContains applies the Contains predicate on the "customer_name" field.
func CustomerNameContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldCustomerName, v))
}

// CustomerNameHasPrefix applies the HasPrefix predicate on the "customer_name" field.
func CustomerNameHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldCustomerName, v))
}

// CustomerNameHasSuffix applies the HasSuffix predicate on the "customer_name" field.
func CustomerNameHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldCustomerName, v))
}

// CustomerNameEqualFold applies the EqualFold predicate on the "customer_name" field.
func CustomerNameEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldCustomerName, v))
}

// CustomerNameContainsFold applies the ContainsFold predicate on the "customer_name" field.
func CustomerNameContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldCustomerName, v))
}

// CustomerPhoneEQ applies the EQ predicate on the "customer_phone" field.
func CustomerPhoneEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldCustomerPhone, v))
}

// CustomerPhoneNEQ applies the NEQ predicate on the "customer_phone" field.
func CustomerPhoneNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldCustomerPhone, v))
}

// CustomerPhoneIn applies the In predicate on the "customer_phone" field.
func CustomerPhoneIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldCustomerPhone, vs...))
}

// CustomerPhoneNotIn applies the NotIn predicate on the "customer_phone" field.
func CustomerPhoneNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldCustomerPhone, vs...))
}

// CustomerPhoneGT applies the GT predicate on the "customer_phone" field.
func CustomerPhoneGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldCustomerPhone, v))
}

// CustomerPhoneGTE applies the GTE predicate on the "customer_phone" field.
func CustomerPhoneGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldCustomerPhone, v))
}

// CustomerPhoneLT applies the LT predicate on the "customer_phone" field.
func CustomerPhoneLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldCustomerPhone, v))
}

// CustomerPhoneLTE applies the LTE predicate on the "customer_phone" field.
func CustomerPhoneLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldCustomerPhone, v))
}

// CustomerPhoneContains applies the Contains predicate on the "customer_phone" field.
func CustomerPhoneContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldCustomerPhone, v))
}

// CustomerPhoneHasPrefix applies the HasPrefix predicate on the "customer_phone" field.
func CustomerPhoneHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldCustomerPhone, v))
}

// CustomerPhoneHasSuffix applies the HasSuffix predicate on the "customer_phone" field.
func CustomerPhoneHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldCustomerPhone, v))
}

// CustomerPhoneEqualFold applies the EqualFold predicate on the "customer_phone" field.
func CustomerPhoneEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldCustomerPhone, v))
}

// CustomerPhoneContainsFold applies the ContainsFold predicate on the "customer_phone" field.
func CustomerPhoneContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldCustomerPhone, v))
}

// AddressEQ applies the EQ predicate on the "address" field.
func AddressEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEQ(FieldAddress, v))
}

// AddressNEQ applies the NEQ predicate on the "address" field.
func AddressNEQ(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNEQ(FieldAddress, v))
}

// AddressIn applies the In predicate on the "address" field.
func AddressIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldIn(FieldAddress, vs...))
}

// AddressNotIn applies the NotIn predicate on the "address" field.
func AddressNotIn(vs ...string) predicate.Ticket {
	return predicate.Ticket(sql.FieldNotIn(FieldAddress, vs...))
}

// AddressGT applies the GT predicate on the "address" field.
func AddressGT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGT(FieldAddress, v))
}

// AddressGTE applies the GTE predicate on the "address" field.
func AddressGTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldGTE(FieldAddress, v))
}

// AddressLT applies the LT predicate on the "address" field.
func AddressLT(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLT(FieldAddress, v))
}

// AddressLTE applies the LTE predicate on the "address" field.
func AddressLTE(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldLTE(FieldAddress, v))
}

// AddressContains applies the Contains predicate on the "address" field.
func AddressContains(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContains(FieldAddress, v))
}

// AddressHasPrefix applies the HasPrefix predicate on the "address" field.
func AddressHasPrefix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasPrefix(FieldAddress, v))
}

// AddressHasSuffix applies the HasSuffix predicate on the "address" field.
func AddressHasSuffix(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldHasSuffix(FieldAddress, v))
}

// AddressIsNil applies the IsNil predicate on the "address" field.
func AddressIsNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldIsNull(FieldAddress))
}

// AddressNotNil applies the NotNil predicate on the "address" field.
func AddressNotNil() predicate.Ticket {
	return predicate.Ticket(sql.FieldNotNull(FieldAddress))
}

// AddressEqualFold applies the EqualFold predicate on the "address" field.
func AddressEqualFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldEqualFold(FieldAddress, v))
}

// AddressContainsFold applies the ContainsFold predicate on the "address" field.
func AddressContainsFold(v string) predicate.Ticket {
	return predicate.Ticket(sql.FieldContainsFold(FieldAddress, v))
}

// HasTechnicians applies the HasEdge predicate on the "technicians" edge.
func HasTechnicians() predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TechniciansTable, TechniciansPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTechniciansWith applies the HasEdge predicate on the "technicians" edge with a given conditions (other predicates).
func HasTechniciansWith(preds ...predicate.Technician) predicate.Ticket {
	return predicate.Ticket(func(s *sql.Selector) {
		step := newTechniciansStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Ticket) predicate.Ticket {
	return predicate.Ticket(sql.NotPredicates(p))
}
