// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlogsColumns holds the columns for the "blogs" table.
	BlogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "publish_schedule", Type: field.TypeTime, Nullable: true},
	}
	// BlogsTable holds the schema information for the "blogs" table.
	BlogsTable = &schema.Table{
		Name:       "blogs",
		Columns:    BlogsColumns,
		PrimaryKey: []*schema.Column{BlogsColumns[0]},
	}
	// NotificationsColumns holds the columns for the "notifications" table.
	NotificationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "is_published", Type: field.TypeBool, Default: false},
		{Name: "publish_schedule", Type: field.TypeTime},
	}
	// NotificationsTable holds the schema information for the "notifications" table.
	NotificationsTable = &schema.Table{
		Name:       "notifications",
		Columns:    NotificationsColumns,
		PrimaryKey: []*schema.Column{NotificationsColumns[0]},
	}
	// TechniciansColumns holds the columns for the "technicians" table.
	TechniciansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "position", Type: field.TypeString, Nullable: true},
	}
	// TechniciansTable holds the schema information for the "technicians" table.
	TechniciansTable = &schema.Table{
		Name:       "technicians",
		Columns:    TechniciansColumns,
		PrimaryKey: []*schema.Column{TechniciansColumns[0]},
	}
	// TicketsColumns holds the columns for the "tickets" table.
	TicketsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "code", Type: field.TypeString},
		{Name: "ticket_type", Type: field.TypeEnum, Enums: []string{"installation", "troubleshoot"}},
		{Name: "priority", Type: field.TypeEnum, Enums: []string{"urgent", "high", "medium", "low"}, Default: "low"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"new", "progress", "hold", "done", "problem", "cancel"}, Default: "new"},
		{Name: "issue", Type: field.TypeString, Size: 2147483647},
		{Name: "technician_response", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "cancel_reason", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "customer_name", Type: field.TypeString},
		{Name: "customer_phone", Type: field.TypeString},
		{Name: "address", Type: field.TypeString, Nullable: true},
	}
	// TicketsTable holds the schema information for the "tickets" table.
	TicketsTable = &schema.Table{
		Name:       "tickets",
		Columns:    TicketsColumns,
		PrimaryKey: []*schema.Column{TicketsColumns[0]},
	}
	// TicketTechniciansColumns holds the columns for the "ticket_technicians" table.
	TicketTechniciansColumns = []*schema.Column{
		{Name: "ticket_id", Type: field.TypeUUID},
		{Name: "technician_id", Type: field.TypeUUID},
	}
	// TicketTechniciansTable holds the schema information for the "ticket_technicians" table.
	TicketTechniciansTable = &schema.Table{
		Name:       "ticket_technicians",
		Columns:    TicketTechniciansColumns,
		PrimaryKey: []*schema.Column{TicketTechniciansColumns[0], TicketTechniciansColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "ticket_technicians_ticket_id",
				Columns:    []*schema.Column{TicketTechniciansColumns[0]},
				RefColumns: []*schema.Column{TicketsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "ticket_technicians_technician_id",
				Columns:    []*schema.Column{TicketTechniciansColumns[1]},
				RefColumns: []*schema.Column{TechniciansColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlogsTable,
		NotificationsTable,
		TechniciansTable,
		TicketsTable,
		TicketTechniciansTable,
	}
)

func init() {
	TicketTechniciansTable.ForeignKeys[0].RefTable = TicketsTable
	TicketTechniciansTable.ForeignKeys[1].RefTable = TechniciansTable
}
