// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini/database/ent/blog"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BlogCreate is the builder for creating a Blog entity.
type BlogCreate struct {
	config
	mutation *BlogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *BlogCreate) SetCreatedAt(v time.Time) *BlogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillableCreatedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BlogCreate) SetUpdatedAt(v time.Time) *BlogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillableUpdatedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *BlogCreate) SetDeletedAt(v time.Time) *BlogCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *BlogCreate) SetNillableDeletedAt(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *BlogCreate) SetTitle(v string) *BlogCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *BlogCreate) SetContent(v string) *BlogCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetIsPublished sets the "is_published" field.
func (_c *BlogCreate) SetIsPublished(v bool) *BlogCreate {
	_c.mutation.SetIsPublished(v)
	return _c
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_c *BlogCreate) SetNillableIsPublished(v *bool) *BlogCreate {
	if v != nil {
		_c.SetIsPublished(*v)
	}
	return _c
}

// SetPublishSchedule sets the "publish_schedule" field.
func (_c *BlogCreate) SetPublishSchedule(v time.Time) *BlogCreate {
	_c.mutation.SetPublishSchedule(v)
	return _c
}

// SetNillablePublishSchedule sets the "publish_schedule" field if the given value is not nil.
func (_c *BlogCreate) SetNillablePublishSchedule(v *time.Time) *BlogCreate {
	if v != nil {
		_c.SetPublishSchedule(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BlogCreate) SetID(v uuid.UUID) *BlogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *BlogCreate) SetNillableID(v *uuid.UUID) *BlogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the BlogMutation object of the builder.
func (_c *BlogCreate) Mutation() *BlogMutation {
	return _c.mutation
}

// Save creates the Blog in the database.
func (_c *BlogCreate) Save(ctx context.Context) (*Blog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BlogCreate) SaveX(ctx context.Context) *Blog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BlogCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if blog.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized blog.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := blog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if blog.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized blog.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := blog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		v := blog.DefaultIsPublished
		_c.mutation.SetIsPublished(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if blog.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized blog.DefaultID (forgotten import ent/runtime?)")
		}
		v := blog.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *BlogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Blog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Blog.updated_at"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Blog.title"`)}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Blog.content"`)}
	}
	if _, ok := _c.mutation.IsPublished(); !ok {
		return &ValidationError{Name: "is_published", err: errors.New(`ent: missing required field "Blog.is_published"`)}
	}
	return nil
}

func (_c *BlogCreate) sqlSave(ctx context.Context) (*Blog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BlogCreate) createSpec() (*Blog, *sqlgraph.CreateSpec) {
	var (
		_node = &Blog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(blog.Table, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(blog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.IsPublished(); ok {
		_spec.SetField(blog.FieldIsPublished, field.TypeBool, value)
		_node.IsPublished = value
	}
	if value, ok := _c.mutation.PublishSchedule(); ok {
		_spec.SetField(blog.FieldPublishSchedule, field.TypeTime, value)
		_node.PublishSchedule = &value
	}
	return _node, _spec
}

// BlogCreateBulk is the builder for creating many Blog entities in bulk.
type BlogCreateBulk struct {
	config
	err      error
	builders []*BlogCreate
}

// Save creates the Blog entities in the database.
func (_c *BlogCreateBulk) Save(ctx context.Context) ([]*Blog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Blog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BlogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BlogCreateBulk) SaveX(ctx context.Context) []*Blog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BlogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BlogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
