// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini/database/ent/blog"
	"mini/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BlogUpdate is the builder for updating Blog entities.
type BlogUpdate struct {
	config
	hooks    []Hook
	mutation *BlogMutation
}

// Where appends a list predicates to the BlogUpdate builder.
func (_u *BlogUpdate) Where(ps ...predicate.Blog) *BlogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogUpdate) SetUpdatedAt(v time.Time) *BlogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BlogUpdate) SetDeletedAt(v time.Time) *BlogUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableDeletedAt(v *time.Time) *BlogUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BlogUpdate) ClearDeletedAt() *BlogUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlogUpdate) SetTitle(v string) *BlogUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableTitle(v *string) *BlogUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogUpdate) SetContent(v string) *BlogUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableContent(v *string) *BlogUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *BlogUpdate) SetIsPublished(v bool) *BlogUpdate {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *BlogUpdate) SetNillableIsPublished(v *bool) *BlogUpdate {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetPublishSchedule sets the "publish_schedule" field.
func (_u *BlogUpdate) SetPublishSchedule(v time.Time) *BlogUpdate {
	_u.mutation.SetPublishSchedule(v)
	return _u
}

// SetNillablePublishSchedule sets the "publish_schedule" field if the given value is not nil.
func (_u *BlogUpdate) SetNillablePublishSchedule(v *time.Time) *BlogUpdate {
	if v != nil {
		_u.SetPublishSchedule(*v)
	}
	return _u
}

// ClearPublishSchedule clears the value of the "publish_schedule" field.
func (_u *BlogUpdate) ClearPublishSchedule() *BlogUpdate {
	_u.mutation.ClearPublishSchedule()
	return _u
}

// Mutation returns the BlogMutation object of the builder.
func (_u *BlogUpdate) Mutation() *BlogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BlogUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BlogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if blog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized blog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := blog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *BlogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(blog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(blog.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishSchedule(); ok {
		_spec.SetField(blog.FieldPublishSchedule, field.TypeTime, value)
	}
	if _u.mutation.PublishScheduleCleared() {
		_spec.ClearField(blog.FieldPublishSchedule, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BlogUpdateOne is the builder for updating a single Blog entity.
type BlogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BlogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BlogUpdateOne) SetUpdatedAt(v time.Time) *BlogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *BlogUpdateOne) SetDeletedAt(v time.Time) *BlogUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableDeletedAt(v *time.Time) *BlogUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *BlogUpdateOne) ClearDeletedAt() *BlogUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTitle sets the "title" field.
func (_u *BlogUpdateOne) SetTitle(v string) *BlogUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableTitle(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *BlogUpdateOne) SetContent(v string) *BlogUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableContent(v *string) *BlogUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetIsPublished sets the "is_published" field.
func (_u *BlogUpdateOne) SetIsPublished(v bool) *BlogUpdateOne {
	_u.mutation.SetIsPublished(v)
	return _u
}

// SetNillableIsPublished sets the "is_published" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillableIsPublished(v *bool) *BlogUpdateOne {
	if v != nil {
		_u.SetIsPublished(*v)
	}
	return _u
}

// SetPublishSchedule sets the "publish_schedule" field.
func (_u *BlogUpdateOne) SetPublishSchedule(v time.Time) *BlogUpdateOne {
	_u.mutation.SetPublishSchedule(v)
	return _u
}

// SetNillablePublishSchedule sets the "publish_schedule" field if the given value is not nil.
func (_u *BlogUpdateOne) SetNillablePublishSchedule(v *time.Time) *BlogUpdateOne {
	if v != nil {
		_u.SetPublishSchedule(*v)
	}
	return _u
}

// ClearPublishSchedule clears the value of the "publish_schedule" field.
func (_u *BlogUpdateOne) ClearPublishSchedule() *BlogUpdateOne {
	_u.mutation.ClearPublishSchedule()
	return _u
}

// Mutation returns the BlogMutation object of the builder.
func (_u *BlogUpdateOne) Mutation() *BlogMutation {
	return _u.mutation
}

// Where appends a list predicates to the BlogUpdate builder.
func (_u *BlogUpdateOne) Where(ps ...predicate.Blog) *BlogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BlogUpdateOne) Select(field string, fields ...string) *BlogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Blog entity.
func (_u *BlogUpdateOne) Save(ctx context.Context) (*Blog, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BlogUpdateOne) SaveX(ctx context.Context) *Blog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BlogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BlogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BlogUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if blog.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized blog.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := blog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *BlogUpdateOne) sqlSave(ctx context.Context) (_node *Blog, err error) {
	_spec := sqlgraph.NewUpdateSpec(blog.Table, blog.Columns, sqlgraph.NewFieldSpec(blog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Blog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, blog.FieldID)
		for _, f := range fields {
			if !blog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != blog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(blog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(blog.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(blog.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(blog.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(blog.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublished(); ok {
		_spec.SetField(blog.FieldIsPublished, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PublishSchedule(); ok {
		_spec.SetField(blog.FieldPublishSchedule, field.TypeTime, value)
	}
	if _u.mutation.PublishScheduleCleared() {
		_spec.ClearField(blog.FieldPublishSchedule, field.TypeTime)
	}
	_node = &Blog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{blog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
