// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mini/database/ent/predicate"
	"mini/database/ent/technician"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TechnicianDelete is the builder for deleting a Technician entity.
type TechnicianDelete struct {
	config
	hooks    []Hook
	mutation *TechnicianMutation
}

// Where appends a list predicates to the TechnicianDelete builder.
func (_d *TechnicianDelete) Where(ps ...predicate.Technician) *TechnicianDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TechnicianDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TechnicianDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TechnicianDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(technician.Table, sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TechnicianDeleteOne is the builder for deleting a single Technician entity.
type TechnicianDeleteOne struct {
	_d *TechnicianDelete
}

// Where appends a list predicates to the TechnicianDelete builder.
func (_d *TechnicianDeleteOne) Where(ps ...predicate.Technician) *TechnicianDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TechnicianDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{technician.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TechnicianDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
