// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini/database/ent/technician"
	"mini/database/ent/ticket"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TechnicianCreate is the builder for creating a Technician entity.
type TechnicianCreate struct {
	config
	mutation *TechnicianMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TechnicianCreate) SetCreatedAt(v time.Time) *TechnicianCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TechnicianCreate) SetNillableCreatedAt(v *time.Time) *TechnicianCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TechnicianCreate) SetUpdatedAt(v time.Time) *TechnicianCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TechnicianCreate) SetNillableUpdatedAt(v *time.Time) *TechnicianCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TechnicianCreate) SetDeletedAt(v time.Time) *TechnicianCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TechnicianCreate) SetNillableDeletedAt(v *time.Time) *TechnicianCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *TechnicianCreate) SetName(v string) *TechnicianCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *TechnicianCreate) SetPhone(v string) *TechnicianCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *TechnicianCreate) SetNillablePhone(v *string) *TechnicianCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *TechnicianCreate) SetPosition(v string) *TechnicianCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *TechnicianCreate) SetNillablePosition(v *string) *TechnicianCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TechnicianCreate) SetID(v uuid.UUID) *TechnicianCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TechnicianCreate) SetNillableID(v *uuid.UUID) *TechnicianCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_c *TechnicianCreate) AddTicketIDs(ids ...uuid.UUID) *TechnicianCreate {
	_c.mutation.AddTicketIDs(ids...)
	return _c
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_c *TechnicianCreate) AddTickets(v ...*Ticket) *TechnicianCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTicketIDs(ids...)
}

// Mutation returns the TechnicianMutation object of the builder.
func (_c *TechnicianCreate) Mutation() *TechnicianMutation {
	return _c.mutation
}

// Save creates the Technician in the database.
func (_c *TechnicianCreate) Save(ctx context.Context) (*Technician, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TechnicianCreate) SaveX(ctx context.Context) *Technician {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TechnicianCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TechnicianCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TechnicianCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if technician.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized technician.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := technician.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if technician.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized technician.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := technician.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if technician.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized technician.DefaultID (forgotten import ent/runtime?)")
		}
		v := technician.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TechnicianCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Technician.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Technician.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Technician.name"`)}
	}
	return nil
}

func (_c *TechnicianCreate) sqlSave(ctx context.Context) (*Technician, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TechnicianCreate) createSpec() (*Technician, *sqlgraph.CreateSpec) {
	var (
		_node = &Technician{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(technician.Table, sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(technician.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(technician.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(technician.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(technician.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(technician.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(technician.FieldPosition, field.TypeString, value)
		_node.Position = value
	}
	if nodes := _c.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TechnicianCreateBulk is the builder for creating many Technician entities in bulk.
type TechnicianCreateBulk struct {
	config
	err      error
	builders []*TechnicianCreate
}

// Save creates the Technician entities in the database.
func (_c *TechnicianCreateBulk) Save(ctx context.Context) ([]*Technician, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Technician, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TechnicianMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TechnicianCreateBulk) SaveX(ctx context.Context) []*Technician {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TechnicianCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TechnicianCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
