// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini/database/ent/predicate"
	"mini/database/ent/technician"
	"mini/database/ent/ticket"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TechnicianUpdate is the builder for updating Technician entities.
type TechnicianUpdate struct {
	config
	hooks    []Hook
	mutation *TechnicianMutation
}

// Where appends a list predicates to the TechnicianUpdate builder.
func (_u *TechnicianUpdate) Where(ps ...predicate.Technician) *TechnicianUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TechnicianUpdate) SetUpdatedAt(v time.Time) *TechnicianUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TechnicianUpdate) SetDeletedAt(v time.Time) *TechnicianUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TechnicianUpdate) SetNillableDeletedAt(v *time.Time) *TechnicianUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TechnicianUpdate) ClearDeletedAt() *TechnicianUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TechnicianUpdate) SetName(v string) *TechnicianUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TechnicianUpdate) SetNillableName(v *string) *TechnicianUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *TechnicianUpdate) SetPhone(v string) *TechnicianUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *TechnicianUpdate) SetNillablePhone(v *string) *TechnicianUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *TechnicianUpdate) ClearPhone() *TechnicianUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetPosition sets the "position" field.
func (_u *TechnicianUpdate) SetPosition(v string) *TechnicianUpdate {
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *TechnicianUpdate) SetNillablePosition(v *string) *TechnicianUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// ClearPosition clears the value of the "position" field.
func (_u *TechnicianUpdate) ClearPosition() *TechnicianUpdate {
	_u.mutation.ClearPosition()
	return _u
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_u *TechnicianUpdate) AddTicketIDs(ids ...uuid.UUID) *TechnicianUpdate {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_u *TechnicianUpdate) AddTickets(v ...*Ticket) *TechnicianUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// Mutation returns the TechnicianMutation object of the builder.
func (_u *TechnicianUpdate) Mutation() *TechnicianMutation {
	return _u.mutation
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (_u *TechnicianUpdate) ClearTickets() *TechnicianUpdate {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (_u *TechnicianUpdate) RemoveTicketIDs(ids ...uuid.UUID) *TechnicianUpdate {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (_u *TechnicianUpdate) RemoveTickets(v ...*Ticket) *TechnicianUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TechnicianUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TechnicianUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TechnicianUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TechnicianUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TechnicianUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if technician.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized technician.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := technician.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *TechnicianUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(technician.Table, technician.Columns, sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(technician.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(technician.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(technician.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(technician.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(technician.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(technician.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(technician.FieldPosition, field.TypeString, value)
	}
	if _u.mutation.PositionCleared() {
		_spec.ClearField(technician.FieldPosition, field.TypeString)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{technician.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TechnicianUpdateOne is the builder for updating a single Technician entity.
type TechnicianUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TechnicianMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TechnicianUpdateOne) SetUpdatedAt(v time.Time) *TechnicianUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TechnicianUpdateOne) SetDeletedAt(v time.Time) *TechnicianUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TechnicianUpdateOne) SetNillableDeletedAt(v *time.Time) *TechnicianUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TechnicianUpdateOne) ClearDeletedAt() *TechnicianUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *TechnicianUpdateOne) SetName(v string) *TechnicianUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TechnicianUpdateOne) SetNillableName(v *string) *TechnicianUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *TechnicianUpdateOne) SetPhone(v string) *TechnicianUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *TechnicianUpdateOne) SetNillablePhone(v *string) *TechnicianUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *TechnicianUpdateOne) ClearPhone() *TechnicianUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetPosition sets the "position" field.
func (_u *TechnicianUpdateOne) SetPosition(v string) *TechnicianUpdateOne {
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *TechnicianUpdateOne) SetNillablePosition(v *string) *TechnicianUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// ClearPosition clears the value of the "position" field.
func (_u *TechnicianUpdateOne) ClearPosition() *TechnicianUpdateOne {
	_u.mutation.ClearPosition()
	return _u
}

// AddTicketIDs adds the "tickets" edge to the Ticket entity by IDs.
func (_u *TechnicianUpdateOne) AddTicketIDs(ids ...uuid.UUID) *TechnicianUpdateOne {
	_u.mutation.AddTicketIDs(ids...)
	return _u
}

// AddTickets adds the "tickets" edges to the Ticket entity.
func (_u *TechnicianUpdateOne) AddTickets(v ...*Ticket) *TechnicianUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTicketIDs(ids...)
}

// Mutation returns the TechnicianMutation object of the builder.
func (_u *TechnicianUpdateOne) Mutation() *TechnicianMutation {
	return _u.mutation
}

// ClearTickets clears all "tickets" edges to the Ticket entity.
func (_u *TechnicianUpdateOne) ClearTickets() *TechnicianUpdateOne {
	_u.mutation.ClearTickets()
	return _u
}

// RemoveTicketIDs removes the "tickets" edge to Ticket entities by IDs.
func (_u *TechnicianUpdateOne) RemoveTicketIDs(ids ...uuid.UUID) *TechnicianUpdateOne {
	_u.mutation.RemoveTicketIDs(ids...)
	return _u
}

// RemoveTickets removes "tickets" edges to Ticket entities.
func (_u *TechnicianUpdateOne) RemoveTickets(v ...*Ticket) *TechnicianUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTicketIDs(ids...)
}

// Where appends a list predicates to the TechnicianUpdate builder.
func (_u *TechnicianUpdateOne) Where(ps ...predicate.Technician) *TechnicianUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TechnicianUpdateOne) Select(field string, fields ...string) *TechnicianUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Technician entity.
func (_u *TechnicianUpdateOne) Save(ctx context.Context) (*Technician, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TechnicianUpdateOne) SaveX(ctx context.Context) *Technician {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TechnicianUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TechnicianUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TechnicianUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if technician.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized technician.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := technician.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *TechnicianUpdateOne) sqlSave(ctx context.Context) (_node *Technician, err error) {
	_spec := sqlgraph.NewUpdateSpec(technician.Table, technician.Columns, sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Technician.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, technician.FieldID)
		for _, f := range fields {
			if !technician.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != technician.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(technician.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(technician.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(technician.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(technician.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(technician.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(technician.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(technician.FieldPosition, field.TypeString, value)
	}
	if _u.mutation.PositionCleared() {
		_spec.ClearField(technician.FieldPosition, field.TypeString)
	}
	if _u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTicketsIDs(); len(nodes) > 0 && !_u.mutation.TicketsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TicketsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   technician.TicketsTable,
			Columns: technician.TicketsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Technician{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{technician.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
