// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini/database/ent/technician"
	"mini/database/ent/ticket"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TicketCreate is the builder for creating a Ticket entity.
type TicketCreate struct {
	config
	mutation *TicketMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *TicketCreate) SetCreatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableCreatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TicketCreate) SetUpdatedAt(v time.Time) *TicketCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableUpdatedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TicketCreate) SetDeletedAt(v time.Time) *TicketCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TicketCreate) SetNillableDeletedAt(v *time.Time) *TicketCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetCode sets the "code" field.
func (_c *TicketCreate) SetCode(v string) *TicketCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetTicketType sets the "ticket_type" field.
func (_c *TicketCreate) SetTicketType(v ticket.TicketType) *TicketCreate {
	_c.mutation.SetTicketType(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *TicketCreate) SetPriority(v ticket.Priority) *TicketCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *TicketCreate) SetNillablePriority(v *ticket.Priority) *TicketCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *TicketCreate) SetStatus(v ticket.Status) *TicketCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TicketCreate) SetNillableStatus(v *ticket.Status) *TicketCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIssue sets the "issue" field.
func (_c *TicketCreate) SetIssue(v string) *TicketCreate {
	_c.mutation.SetIssue(v)
	return _c
}

// SetTechnicianResponse sets the "technician_response" field.
func (_c *TicketCreate) SetTechnicianResponse(v string) *TicketCreate {
	_c.mutation.SetTechnicianResponse(v)
	return _c
}

// SetNillableTechnicianResponse sets the "technician_response" field if the given value is not nil.
func (_c *TicketCreate) SetNillableTechnicianResponse(v *string) *TicketCreate {
	if v != nil {
		_c.SetTechnicianResponse(*v)
	}
	return _c
}

// SetCancelReason sets the "cancel_reason" field.
func (_c *TicketCreate) SetCancelReason(v string) *TicketCreate {
	_c.mutation.SetCancelReason(v)
	return _c
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_c *TicketCreate) SetNillableCancelReason(v *string) *TicketCreate {
	if v != nil {
		_c.SetCancelReason(*v)
	}
	return _c
}

// SetCustomerName sets the "customer_name" field.
func (_c *TicketCreate) SetCustomerName(v string) *TicketCreate {
	_c.mutation.SetCustomerName(v)
	return _c
}

// SetCustomerPhone sets the "customer_phone" field.
func (_c *TicketCreate) SetCustomerPhone(v string) *TicketCreate {
	_c.mutation.SetCustomerPhone(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *TicketCreate) SetAddress(v string) *TicketCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_c *TicketCreate) SetNillableAddress(v *string) *TicketCreate {
	if v != nil {
		_c.SetAddress(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TicketCreate) SetID(v uuid.UUID) *TicketCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *TicketCreate) SetNillableID(v *uuid.UUID) *TicketCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddTechnicianIDs adds the "technicians" edge to the Technician entity by IDs.
func (_c *TicketCreate) AddTechnicianIDs(ids ...uuid.UUID) *TicketCreate {
	_c.mutation.AddTechnicianIDs(ids...)
	return _c
}

// AddTechnicians adds the "technicians" edges to the Technician entity.
func (_c *TicketCreate) AddTechnicians(v ...*Technician) *TicketCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTechnicianIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_c *TicketCreate) Mutation() *TicketMutation {
	return _c.mutation
}

// Save creates the Ticket in the database.
func (_c *TicketCreate) Save(ctx context.Context) (*Ticket, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TicketCreate) SaveX(ctx context.Context) *Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TicketCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if ticket.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized ticket.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := ticket.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if ticket.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ticket.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ticket.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := ticket.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ticket.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TechnicianResponse(); !ok {
		v := ticket.DefaultTechnicianResponse
		_c.mutation.SetTechnicianResponse(v)
	}
	if _, ok := _c.mutation.CancelReason(); !ok {
		v := ticket.DefaultCancelReason
		_c.mutation.SetCancelReason(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		if ticket.DefaultID == nil {
			return fmt.Errorf("ent: uninitialized ticket.DefaultID (forgotten import ent/runtime?)")
		}
		v := ticket.DefaultID()
		_c.mutation.SetID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TicketCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Ticket.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Ticket.updated_at"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Ticket.code"`)}
	}
	if _, ok := _c.mutation.TicketType(); !ok {
		return &ValidationError{Name: "ticket_type", err: errors.New(`ent: missing required field "Ticket.ticket_type"`)}
	}
	if v, ok := _c.mutation.TicketType(); ok {
		if err := ticket.TicketTypeValidator(v); err != nil {
			return &ValidationError{Name: "ticket_type", err: fmt.Errorf(`ent: validator failed for field "Ticket.ticket_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "Ticket.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := ticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Ticket.priority": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Ticket.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Issue(); !ok {
		return &ValidationError{Name: "issue", err: errors.New(`ent: missing required field "Ticket.issue"`)}
	}
	if _, ok := _c.mutation.TechnicianResponse(); !ok {
		return &ValidationError{Name: "technician_response", err: errors.New(`ent: missing required field "Ticket.technician_response"`)}
	}
	if _, ok := _c.mutation.CancelReason(); !ok {
		return &ValidationError{Name: "cancel_reason", err: errors.New(`ent: missing required field "Ticket.cancel_reason"`)}
	}
	if _, ok := _c.mutation.CustomerName(); !ok {
		return &ValidationError{Name: "customer_name", err: errors.New(`ent: missing required field "Ticket.customer_name"`)}
	}
	if _, ok := _c.mutation.CustomerPhone(); !ok {
		return &ValidationError{Name: "customer_phone", err: errors.New(`ent: missing required field "Ticket.customer_phone"`)}
	}
	return nil
}

func (_c *TicketCreate) sqlSave(ctx context.Context) (*Ticket, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TicketCreate) createSpec() (*Ticket, *sqlgraph.CreateSpec) {
	var (
		_node = &Ticket{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ticket.Table, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ticket.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(ticket.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(ticket.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.TicketType(); ok {
		_spec.SetField(ticket.FieldTicketType, field.TypeEnum, value)
		_node.TicketType = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeEnum, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Issue(); ok {
		_spec.SetField(ticket.FieldIssue, field.TypeString, value)
		_node.Issue = value
	}
	if value, ok := _c.mutation.TechnicianResponse(); ok {
		_spec.SetField(ticket.FieldTechnicianResponse, field.TypeString, value)
		_node.TechnicianResponse = value
	}
	if value, ok := _c.mutation.CancelReason(); ok {
		_spec.SetField(ticket.FieldCancelReason, field.TypeString, value)
		_node.CancelReason = value
	}
	if value, ok := _c.mutation.CustomerName(); ok {
		_spec.SetField(ticket.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = value
	}
	if value, ok := _c.mutation.CustomerPhone(); ok {
		_spec.SetField(ticket.FieldCustomerPhone, field.TypeString, value)
		_node.CustomerPhone = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(ticket.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if nodes := _c.mutation.TechniciansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TicketCreateBulk is the builder for creating many Ticket entities in bulk.
type TicketCreateBulk struct {
	config
	err      error
	builders []*TicketCreate
}

// Save creates the Ticket entities in the database.
func (_c *TicketCreateBulk) Save(ctx context.Context) ([]*Ticket, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Ticket, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TicketMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TicketCreateBulk) SaveX(ctx context.Context) []*Ticket {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TicketCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TicketCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
