// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"mini/database/ent/ticket"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Ticket is the model entity for the Ticket schema.
type Ticket struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// TicketType holds the value of the "ticket_type" field.
	TicketType ticket.TicketType `json:"ticket_type,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority ticket.Priority `json:"priority,omitempty"`
	// Status holds the value of the "status" field.
	Status ticket.Status `json:"status,omitempty"`
	// Issue holds the value of the "issue" field.
	Issue string `json:"issue,omitempty"`
	// TechnicianResponse holds the value of the "technician_response" field.
	TechnicianResponse string `json:"technician_response,omitempty"`
	// CancelReason holds the value of the "cancel_reason" field.
	CancelReason string `json:"cancel_reason,omitempty"`
	// CustomerName holds the value of the "customer_name" field.
	CustomerName string `json:"customer_name,omitempty"`
	// CustomerPhone holds the value of the "customer_phone" field.
	CustomerPhone string `json:"customer_phone,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketQuery when eager-loading is set.
	Edges        TicketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketEdges holds the relations/edges for other nodes in the graph.
type TicketEdges struct {
	// Technicians holds the value of the technicians edge.
	Technicians []*Technician `json:"technicians,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TechniciansOrErr returns the Technicians value or an error if the edge
// was not loaded in eager-loading.
func (e TicketEdges) TechniciansOrErr() ([]*Technician, error) {
	if e.loadedTypes[0] {
		return e.Technicians, nil
	}
	return nil, &NotLoadedError{edge: "technicians"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Ticket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticket.FieldCode, ticket.FieldTicketType, ticket.FieldPriority, ticket.FieldStatus, ticket.FieldIssue, ticket.FieldTechnicianResponse, ticket.FieldCancelReason, ticket.FieldCustomerName, ticket.FieldCustomerPhone, ticket.FieldAddress:
			values[i] = new(sql.NullString)
		case ticket.FieldCreatedAt, ticket.FieldUpdatedAt, ticket.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case ticket.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Ticket fields.
func (_m *Ticket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ticket.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ticket.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ticket.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case ticket.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case ticket.FieldTicketType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_type", values[i])
			} else if value.Valid {
				_m.TicketType = ticket.TicketType(value.String)
			}
		case ticket.FieldPriority:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = ticket.Priority(value.String)
			}
		case ticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = ticket.Status(value.String)
			}
		case ticket.FieldIssue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issue", values[i])
			} else if value.Valid {
				_m.Issue = value.String
			}
		case ticket.FieldTechnicianResponse:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field technician_response", values[i])
			} else if value.Valid {
				_m.TechnicianResponse = value.String
			}
		case ticket.FieldCancelReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cancel_reason", values[i])
			} else if value.Valid {
				_m.CancelReason = value.String
			}
		case ticket.FieldCustomerName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_name", values[i])
			} else if value.Valid {
				_m.CustomerName = value.String
			}
		case ticket.FieldCustomerPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field customer_phone", values[i])
			} else if value.Valid {
				_m.CustomerPhone = value.String
			}
		case ticket.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Ticket.
// This includes values selected through modifiers, order, etc.
func (_m *Ticket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTechnicians queries the "technicians" edge of the Ticket entity.
func (_m *Ticket) QueryTechnicians() *TechnicianQuery {
	return NewTicketClient(_m.config).QueryTechnicians(_m)
}

// Update returns a builder for updating this Ticket.
// Note that you need to call Ticket.Unwrap() before calling this method if this Ticket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Ticket) Update() *TicketUpdateOne {
	return NewTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Ticket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Ticket) Unwrap() *Ticket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Ticket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Ticket) String() string {
	var builder strings.Builder
	builder.WriteString("Ticket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("ticket_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketType))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("issue=")
	builder.WriteString(_m.Issue)
	builder.WriteString(", ")
	builder.WriteString("technician_response=")
	builder.WriteString(_m.TechnicianResponse)
	builder.WriteString(", ")
	builder.WriteString("cancel_reason=")
	builder.WriteString(_m.CancelReason)
	builder.WriteString(", ")
	builder.WriteString("customer_name=")
	builder.WriteString(_m.CustomerName)
	builder.WriteString(", ")
	builder.WriteString("customer_phone=")
	builder.WriteString(_m.CustomerPhone)
	builder.WriteString(", ")
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteByte(')')
	return builder.String()
}

// Tickets is a parsable slice of Ticket.
type Tickets []*Ticket
