// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"mini/database/ent/predicate"
	"mini/database/ent/technician"
	"mini/database/ent/ticket"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TicketUpdate is the builder for updating Ticket entities.
type TicketUpdate struct {
	config
	hooks    []Hook
	mutation *TicketMutation
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdate) Where(ps ...predicate.Ticket) *TicketUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TicketUpdate) SetUpdatedAt(v time.Time) *TicketUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TicketUpdate) SetDeletedAt(v time.Time) *TicketUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableDeletedAt(v *time.Time) *TicketUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TicketUpdate) ClearDeletedAt() *TicketUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *TicketUpdate) SetCode(v string) *TicketUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableCode(v *string) *TicketUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetTicketType sets the "ticket_type" field.
func (_u *TicketUpdate) SetTicketType(v ticket.TicketType) *TicketUpdate {
	_u.mutation.SetTicketType(v)
	return _u
}

// SetNillableTicketType sets the "ticket_type" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableTicketType(v *ticket.TicketType) *TicketUpdate {
	if v != nil {
		_u.SetTicketType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TicketUpdate) SetPriority(v ticket.Priority) *TicketUpdate {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TicketUpdate) SetNillablePriority(v *ticket.Priority) *TicketUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TicketUpdate) SetStatus(v ticket.Status) *TicketUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableStatus(v *ticket.Status) *TicketUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssue sets the "issue" field.
func (_u *TicketUpdate) SetIssue(v string) *TicketUpdate {
	_u.mutation.SetIssue(v)
	return _u
}

// SetNillableIssue sets the "issue" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableIssue(v *string) *TicketUpdate {
	if v != nil {
		_u.SetIssue(*v)
	}
	return _u
}

// SetTechnicianResponse sets the "technician_response" field.
func (_u *TicketUpdate) SetTechnicianResponse(v string) *TicketUpdate {
	_u.mutation.SetTechnicianResponse(v)
	return _u
}

// SetNillableTechnicianResponse sets the "technician_response" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableTechnicianResponse(v *string) *TicketUpdate {
	if v != nil {
		_u.SetTechnicianResponse(*v)
	}
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *TicketUpdate) SetCancelReason(v string) *TicketUpdate {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableCancelReason(v *string) *TicketUpdate {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// SetCustomerName sets the "customer_name" field.
func (_u *TicketUpdate) SetCustomerName(v string) *TicketUpdate {
	_u.mutation.SetCustomerName(v)
	return _u
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableCustomerName(v *string) *TicketUpdate {
	if v != nil {
		_u.SetCustomerName(*v)
	}
	return _u
}

// SetCustomerPhone sets the "customer_phone" field.
func (_u *TicketUpdate) SetCustomerPhone(v string) *TicketUpdate {
	_u.mutation.SetCustomerPhone(v)
	return _u
}

// SetNillableCustomerPhone sets the "customer_phone" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableCustomerPhone(v *string) *TicketUpdate {
	if v != nil {
		_u.SetCustomerPhone(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *TicketUpdate) SetAddress(v string) *TicketUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TicketUpdate) SetNillableAddress(v *string) *TicketUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *TicketUpdate) ClearAddress() *TicketUpdate {
	_u.mutation.ClearAddress()
	return _u
}

// AddTechnicianIDs adds the "technicians" edge to the Technician entity by IDs.
func (_u *TicketUpdate) AddTechnicianIDs(ids ...uuid.UUID) *TicketUpdate {
	_u.mutation.AddTechnicianIDs(ids...)
	return _u
}

// AddTechnicians adds the "technicians" edges to the Technician entity.
func (_u *TicketUpdate) AddTechnicians(v ...*Technician) *TicketUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTechnicianIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdate) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearTechnicians clears all "technicians" edges to the Technician entity.
func (_u *TicketUpdate) ClearTechnicians() *TicketUpdate {
	_u.mutation.ClearTechnicians()
	return _u
}

// RemoveTechnicianIDs removes the "technicians" edge to Technician entities by IDs.
func (_u *TicketUpdate) RemoveTechnicianIDs(ids ...uuid.UUID) *TicketUpdate {
	_u.mutation.RemoveTechnicianIDs(ids...)
	return _u
}

// RemoveTechnicians removes "technicians" edges to Technician entities.
func (_u *TicketUpdate) RemoveTechnicians(v ...*Technician) *TicketUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTechnicianIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TicketUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TicketUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TicketUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ticket.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ticket.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdate) check() error {
	if v, ok := _u.mutation.TicketType(); ok {
		if err := ticket.TicketTypeValidator(v); err != nil {
			return &ValidationError{Name: "ticket_type", err: fmt.Errorf(`ent: validator failed for field "Ticket.ticket_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := ticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Ticket.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TicketUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ticket.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ticket.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(ticket.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TicketType(); ok {
		_spec.SetField(ticket.FieldTicketType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Issue(); ok {
		_spec.SetField(ticket.FieldIssue, field.TypeString, value)
	}
	if value, ok := _u.mutation.TechnicianResponse(); ok {
		_spec.SetField(ticket.FieldTechnicianResponse, field.TypeString, value)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(ticket.FieldCancelReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerName(); ok {
		_spec.SetField(ticket.FieldCustomerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerPhone(); ok {
		_spec.SetField(ticket.FieldCustomerPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(ticket.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(ticket.FieldAddress, field.TypeString)
	}
	if _u.mutation.TechniciansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTechniciansIDs(); len(nodes) > 0 && !_u.mutation.TechniciansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TechniciansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TicketUpdateOne is the builder for updating a single Ticket entity.
type TicketUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TicketMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TicketUpdateOne) SetUpdatedAt(v time.Time) *TicketUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TicketUpdateOne) SetDeletedAt(v time.Time) *TicketUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableDeletedAt(v *time.Time) *TicketUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TicketUpdateOne) ClearDeletedAt() *TicketUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetCode sets the "code" field.
func (_u *TicketUpdateOne) SetCode(v string) *TicketUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableCode(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetTicketType sets the "ticket_type" field.
func (_u *TicketUpdateOne) SetTicketType(v ticket.TicketType) *TicketUpdateOne {
	_u.mutation.SetTicketType(v)
	return _u
}

// SetNillableTicketType sets the "ticket_type" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableTicketType(v *ticket.TicketType) *TicketUpdateOne {
	if v != nil {
		_u.SetTicketType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *TicketUpdateOne) SetPriority(v ticket.Priority) *TicketUpdateOne {
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillablePriority(v *ticket.Priority) *TicketUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TicketUpdateOne) SetStatus(v ticket.Status) *TicketUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableStatus(v *ticket.Status) *TicketUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIssue sets the "issue" field.
func (_u *TicketUpdateOne) SetIssue(v string) *TicketUpdateOne {
	_u.mutation.SetIssue(v)
	return _u
}

// SetNillableIssue sets the "issue" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableIssue(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetIssue(*v)
	}
	return _u
}

// SetTechnicianResponse sets the "technician_response" field.
func (_u *TicketUpdateOne) SetTechnicianResponse(v string) *TicketUpdateOne {
	_u.mutation.SetTechnicianResponse(v)
	return _u
}

// SetNillableTechnicianResponse sets the "technician_response" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableTechnicianResponse(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetTechnicianResponse(*v)
	}
	return _u
}

// SetCancelReason sets the "cancel_reason" field.
func (_u *TicketUpdateOne) SetCancelReason(v string) *TicketUpdateOne {
	_u.mutation.SetCancelReason(v)
	return _u
}

// SetNillableCancelReason sets the "cancel_reason" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableCancelReason(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetCancelReason(*v)
	}
	return _u
}

// SetCustomerName sets the "customer_name" field.
func (_u *TicketUpdateOne) SetCustomerName(v string) *TicketUpdateOne {
	_u.mutation.SetCustomerName(v)
	return _u
}

// SetNillableCustomerName sets the "customer_name" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableCustomerName(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetCustomerName(*v)
	}
	return _u
}

// SetCustomerPhone sets the "customer_phone" field.
func (_u *TicketUpdateOne) SetCustomerPhone(v string) *TicketUpdateOne {
	_u.mutation.SetCustomerPhone(v)
	return _u
}

// SetNillableCustomerPhone sets the "customer_phone" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableCustomerPhone(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetCustomerPhone(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *TicketUpdateOne) SetAddress(v string) *TicketUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *TicketUpdateOne) SetNillableAddress(v *string) *TicketUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// ClearAddress clears the value of the "address" field.
func (_u *TicketUpdateOne) ClearAddress() *TicketUpdateOne {
	_u.mutation.ClearAddress()
	return _u
}

// AddTechnicianIDs adds the "technicians" edge to the Technician entity by IDs.
func (_u *TicketUpdateOne) AddTechnicianIDs(ids ...uuid.UUID) *TicketUpdateOne {
	_u.mutation.AddTechnicianIDs(ids...)
	return _u
}

// AddTechnicians adds the "technicians" edges to the Technician entity.
func (_u *TicketUpdateOne) AddTechnicians(v ...*Technician) *TicketUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTechnicianIDs(ids...)
}

// Mutation returns the TicketMutation object of the builder.
func (_u *TicketUpdateOne) Mutation() *TicketMutation {
	return _u.mutation
}

// ClearTechnicians clears all "technicians" edges to the Technician entity.
func (_u *TicketUpdateOne) ClearTechnicians() *TicketUpdateOne {
	_u.mutation.ClearTechnicians()
	return _u
}

// RemoveTechnicianIDs removes the "technicians" edge to Technician entities by IDs.
func (_u *TicketUpdateOne) RemoveTechnicianIDs(ids ...uuid.UUID) *TicketUpdateOne {
	_u.mutation.RemoveTechnicianIDs(ids...)
	return _u
}

// RemoveTechnicians removes "technicians" edges to Technician entities.
func (_u *TicketUpdateOne) RemoveTechnicians(v ...*Technician) *TicketUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTechnicianIDs(ids...)
}

// Where appends a list predicates to the TicketUpdate builder.
func (_u *TicketUpdateOne) Where(ps ...predicate.Ticket) *TicketUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TicketUpdateOne) Select(field string, fields ...string) *TicketUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Ticket entity.
func (_u *TicketUpdateOne) Save(ctx context.Context) (*Ticket, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TicketUpdateOne) SaveX(ctx context.Context) *Ticket {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TicketUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TicketUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TicketUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if ticket.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized ticket.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := ticket.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TicketUpdateOne) check() error {
	if v, ok := _u.mutation.TicketType(); ok {
		if err := ticket.TicketTypeValidator(v); err != nil {
			return &ValidationError{Name: "ticket_type", err: fmt.Errorf(`ent: validator failed for field "Ticket.ticket_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Priority(); ok {
		if err := ticket.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "Ticket.priority": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := ticket.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Ticket.status": %w`, err)}
		}
	}
	return nil
}

func (_u *TicketUpdateOne) sqlSave(ctx context.Context) (_node *Ticket, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ticket.Table, ticket.Columns, sqlgraph.NewFieldSpec(ticket.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Ticket.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ticket.FieldID)
		for _, f := range fields {
			if !ticket.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ticket.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ticket.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(ticket.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(ticket.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(ticket.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.TicketType(); ok {
		_spec.SetField(ticket.FieldTicketType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(ticket.FieldPriority, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ticket.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Issue(); ok {
		_spec.SetField(ticket.FieldIssue, field.TypeString, value)
	}
	if value, ok := _u.mutation.TechnicianResponse(); ok {
		_spec.SetField(ticket.FieldTechnicianResponse, field.TypeString, value)
	}
	if value, ok := _u.mutation.CancelReason(); ok {
		_spec.SetField(ticket.FieldCancelReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerName(); ok {
		_spec.SetField(ticket.FieldCustomerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.CustomerPhone(); ok {
		_spec.SetField(ticket.FieldCustomerPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(ticket.FieldAddress, field.TypeString, value)
	}
	if _u.mutation.AddressCleared() {
		_spec.ClearField(ticket.FieldAddress, field.TypeString)
	}
	if _u.mutation.TechniciansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTechniciansIDs(); len(nodes) > 0 && !_u.mutation.TechniciansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TechniciansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   ticket.TechniciansTable,
			Columns: ticket.TechniciansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(technician.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Ticket{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ticket.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
